### 1.out

In [2]:
import torch

In [ ]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
out1 = torch.outer(v1, v2)
# torch.outer(v1, v2) 计算两个向量的外积，结果是一个矩阵，其中第 i 行第 j 列的元素是 v1[i] * v2[j]。
print(out1)


tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])


### 2.where

In [4]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([10,20,30,40,50])

condition = x > 3
result = torch.where(condition, x, y)
# x中的元素满足condition，则选择x中的元素，否则选择y中的元素

print(result)  # 输出: tensor([10, 20, 30,  4,  5])

tensor([10, 20, 30,  4,  5])


### 3.arange
输出等差序列

torch.arange(起始数字（包含在序列中）,终止数字（不包含在序列中）,差值)

In [5]:
t = torch.arange(0,10,2)
print(t)

t1 = torch.arange(5,0,-1)
print(t1)

tensor([0, 2, 4, 6, 8])
tensor([5, 4, 3, 2, 1])


### 4.cat
对指定维度进行拼接

In [6]:
t1 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t2 = torch.tensor([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
print(t1.shape)  # 输出: torch.Size([2, 2, 3])

result = torch.cat((t1, t2), dim=0)
print(result.shape)  # 输出: torch.Size([4, 2, 3])

result = torch.cat((t1, t2), dim=1)
print(result.shape)  # 输出: torch.Size([2, 4, 3])

result = torch.cat((t1, t2), dim=2)
print(result.shape)  # 输出: torch.Size([2, 2, 6])


torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
torch.Size([2, 4, 3])
torch.Size([2, 2, 6])


### 5.unsqueeze
在第指定维增加一个维度

In [7]:
t1 = torch.tensor([1,2,3])
t2 = t1.unsqueeze(0)  # 在第0维增加一个维度
print(t1.shape)
print(t2.shape)

torch.Size([3])
torch.Size([1, 3])


### 6.dropout
- 每个元素有 p 的概率被丢弃
- 每个元素有 p 的概率被保留

PyTorch 的 Dropout 会对保留下来的元素做缩放，以此让让整体期望值不变，缩放系数是：1 / (1 - p)

In [9]:
import torch.nn as nn

dropout_layer = nn.Dropout(p=0.5)  # 创建一个Dropout层，丢弃概率为0.5

t1 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
t2 = dropout_layer(t1)  # 应用Dropout层
print(t2)

tensor([[0., 0., 6.],
        [0., 0., 0.]])


### 7.view
改变张量形状

In [10]:
t = torch.tensor([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

t_view1 = t.view(3, 4)  # 将张量t重新形状为3行4列
t_view2 = t.view(-1, 3)  # 将张量t重新形状为若干行3列，-1表示自动计算行数
print(t_view1)
print(t_view2)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


### 8.reshape

In [11]:
x = torch.arange(0, 10)

y = torch.reshape(x, (2, 5))  # 将x重新形状为2行5列
z = torch.reshape(x, (5, -1))  # 将x重新形状为5行2列

print(y)
print(z)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


#### view 和 reshape 都能改张量形状，但核心区别是：
> view 要求张量在内存里是连续的；reshape 更宽松，必要时会自动复制一份连续内存。

view() 只能在不搬动数据的情况下改变形状，所以它需要内存布局能直接解释成新形状。
像 transpose 后的这种张量，很多时候就不能直接 view()。而 reshape() 发现不行时，会帮你复制并整理成连续内存。

对 transpose（转置）进行解释：

当使用`y = x.transpose(0, 1)`，将x的0，1维度进行转置时，并**不会创建一个新的内存，而是将y设置为对x内存的不同读取方法**。因此，y的底层内存是不连续的

### 9.transpose
转置

In [14]:
t1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
t2 = t1.transpose(0, 1)  # 转置操作，将第0维和第1维交换
print(t2)



tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


### 10.triu
对矩阵进行操作

In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(torch.triu(x))  # 输出上三角矩阵

print(torch.triu(x, diagonal=1))  # 输出上三角矩阵，偏移量为1
print(torch.triu(x, diagonal=-1))  # 输出上三角矩阵，偏移量为-1

print(torch.tril(x))  # 输出下三角矩阵

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])
tensor([[0, 2, 3],
        [0, 0, 6],
        [0, 0, 0]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 8, 9]])
tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])


### 11.expand
**expand 用来把某些维度为 1 的张量“广播”成更大的形状，而且通常不复制真实数据。**
- expand 得到的 y 通常不是新复制出来的一大块数据，而是一个“视图”。它记录了新的 shape 和新的读取规则，让某个维度反复读取同一个底层元素。
- 使用 expand 时，想要被扩大的那个维度，在广播之前必须是 1
- expand 只能把大小为 1 的维度扩成更大；如果没有这个维度，就先用 unsqueeze 加出来

In [16]:
x = torch.tensor([[1],
                  [2],
                  [3]])

print(x.shape)  # [3, 1]

y = x.expand(3, 4)

print(y)

torch.Size([3, 1])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
